name: Generate GitHub Stats Image

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:       # allows manual runs

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats SVG
        run: |
          curl -H "Authorization: token ${{ .env.GH_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api?username=vish2285&show_icons=true&theme=nightowl&count_private=true" \
            -o stats.svg

      - name: Commit and push updated stats
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add stats.svg
          git commit -m "Update GitHub stats"
          git push